// GENERATED BY gen.mjs in this folder. Edit that, not this, or the
// records stop matching the accepted Home's list. Regenerate with:
// node src/app/preview/performance-lab/gen.mjs
//
// 87 settled picks, 49-38, engineered so Lab's chips read the exact
// records Home's top list shows: Moneyline 30-16, Premier League
// 14-8, Low odds 18-11, Singles 24-18, Player Props 7-11, and the
// dollars land on Home's figures to within a dollar. Demo data only,
// never real user data: the previews are public.

import type { BetWithLegs, Leg } from "@/lib/types";

function daysAgo(days: number, hour = 18): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

let n = 0;
function l(
  sport: Leg["sport"],
  description: string,
  odds: number,
  won: boolean,
  subcategory: string,
  market: string,
  period: string | null,
  competition: string | null
): Omit<Leg, "id"> {
  return {
    sport,
    description,
    odds,
    result: won ? "won" : "lost",
    subcategory,
    market,
    period,
    competition,
    provider_market: null,
  };
}

function bet(stake: number, days: number, legs: Omit<Leg, "id">[]): BetWithLegs {
  n += 1;
  const won = legs.every((x) => x.result === "won");
  const odds =
    Math.round(legs.reduce((acc, x) => acc * (x.odds ?? 1), 1) * 10000) / 10000;
  return {
    id: `lab${n}`,
    stake,
    total_odds: odds,
    status: won ? "won" : "lost",
    placed_at: daysAgo(days, 9),
    settled_at: daysAgo(days),
    payout: won ? Math.round(stake * odds * 100) / 100 : 0,
    cashed_out: false,
    bet_buys: [],
    legs: legs.map((x, i) => ({ ...x, id: `lab${n}-${i}` })),
  };
}

export const labBets: BetWithLegs[] = [
  bet(320, 90, [l("Football", "Vinicius 2+ shots on target", 3.12, false, "Player Props", "Shots", null, "La Liga")]),
  bet(275.04, 88, [l("Crypto", "BTC down this week", 2.26, false, "Price Direction", "Price Direction", null, null)]),
  bet(142.4, 87, [l("Football", "Everton to win", 1.49, true, "Moneyline", "Match Winner", null, "Premier League"), l("Football", "Liverpool to win", 1.6, false, "Moneyline", "Match Winner", "1st Half", "Premier League"), l("Football", "Man City to win", 1.32, false, "Moneyline", "Match Winner", "2nd Half", "Premier League")]),
  bet(142.4, 85, [l("Football", "Wolves to win", 1.7, true, "Moneyline", "Match Winner", null, "Premier League"), l("Football", "Mbappe to score", 4.73, false, "Player Props", "Goalscorer", null, "Premier League"), l("Football", "Haaland to score", 3.71, false, "Player Props", "Goalscorer", null, "Premier League")]),
  bet(320, 84, [l("American Football", "Hurts over 230.5 yards", 2.7, false, "Player Props", "Passing Yards", null, "NFL")]),
  bet(142.4, 82, [l("Tennis", "Rune to win", 1.49, true, "Moneyline", "Match Winner", null, "ATP"), l("Tennis", "Ruud to win", 1.58, false, "Moneyline", "Match Winner", "1st Set", "ATP"), l("Tennis", "Fritz to win", 2.19, false, "Moneyline", "Match Winner", null, "ATP")]),
  bet(199.35, 81, [l("Baseball", "Yankees to win", 1.49, true, "Moneyline", "Match Winner", null, "MLB"), l("Baseball", "Astros to win", 1.63, true, "Moneyline", "Match Winner", null, "MLB")]),
  bet(35.48, 79, [l("Football", "Under 2.5 goals", 1.71, true, "Totals (Over/Under)", "Match Total", null, "Premier League")]),
  bet(142.4, 78, [l("Basketball", "Thunder to win", 2.21, true, "Moneyline", "Match Winner", "1st Half", "NBA"), l("Basketball", "Celtics to win", 1.66, false, "Moneyline", "Match Winner", "1st Half", "NBA"), l("Basketball", "Nuggets to win", 1.56, false, "Moneyline", "Match Winner", null, "NBA")]),
  bet(25.23, 76, [l("Tennis", "Medvedev to win", 1.76, true, "Moneyline", "Match Winner", null, "ATP")]),
  bet(39.83, 75, [l("Football", "Kane to score", 1.89, true, "Player Props", "Goalscorer", null, "International")]),
  bet(142.4, 73, [l("Football", "Villa to win", 1.59, true, "Moneyline", "Match Winner", null, "Premier League"), l("Football", "Newcastle to win", 1.33, false, "Moneyline", "Match Winner", null, "Premier League"), l("Football", "Palace to win", 1.44, false, "Moneyline", "Match Winner", null, "Premier League")]),
  bet(183.99, 71, [l("Crypto", "SOL up this week", 1.9, true, "Price Direction", "Price Direction", null, null)]),
  bet(142.4, 70, [l("Basketball", "Suns to win", 2.24, true, "Moneyline", "Match Winner", null, "NBA"), l("Basketball", "Curry over 24.5 points", 4.07, false, "Player Props", "Points", "4th Quarter", "NBA"), l("Basketball", "Brunson over 25.5 points", 3.52, false, "Player Props", "Points", null, "NBA")]),
  bet(193.06, 68, [l("Football", "Bayern -1.5", 2.11, true, "Spread / Handicap", "Spread", null, "Champions League")]),
  bet(238.61, 67, [l("Tennis", "Sinner to win", 2, true, "Moneyline", "Match Winner", null, "ATP")]),
  bet(142.4, 65, [l("Basketball", "Knicks to win", 1.9, true, "Moneyline", "Match Winner", null, "NBA"), l("Basketball", "Bucks to win", 2.94, false, "Moneyline", "Match Winner", null, "NBA"), l("Basketball", "Doncic over 30.5 points", 3.11, false, "Player Props", "Points", "3rd Quarter", "NBA")]),
  bet(37.71, 64, [l("American Football", "Mahomes over 270.5 yards", 2.02, true, "Player Props", "Passing Yards", null, "NFL")]),
  bet(142.4, 62, [l("Football", "Chelsea to win", 1.65, true, "Moneyline", "Match Winner", null, "Premier League"), l("Football", "City -1", 2, false, "Spread / Handicap", "Spread", null, "Premier League"), l("Football", "Both teams to score", 1.87, false, "Match Props", "BTTS", null, "Premier League")]),
  bet(191.61, 61, [l("Crypto", "Gold up this week", 2.07, true, "Price Direction", "Price Direction", null, null)]),
  bet(153.28, 59, [l("Ice Hockey", "Under 6.5 goals", 1.34, true, "Totals (Over/Under)", "Match Total", null, "NHL"), l("Ice Hockey", "Over 5.5 goals", 2.81, true, "Totals (Over/Under)", "Match Total", null, "NHL")]),
  bet(142.4, 58, [l("Baseball", "Dodgers to win", 2, true, "Moneyline", "Match Winner", null, "MLB"), l("Baseball", "Braves to win", 1.72, false, "Moneyline", "Match Winner", null, "MLB"), l("Baseball", "Dodgers -1.5", 2.84, false, "Spread / Handicap", "Spread", null, "MLB")]),
  bet(237.69, 56, [l("Football", "Villarreal to win", 2.16, true, "Moneyline", "Match Winner", null, "La Liga")]),
  bet(142.4, 54, [l("Crypto", "ETH down today", 4.38, true, "Price Direction", "Price Direction", null, null), l("Crypto", "ETH up today", 1.67, false, "Price Direction", "Price Direction", null, null), l("Crypto", "BTC up this week", 1.36, false, "Price Direction", "Price Direction", null, null)]),
  bet(142.86, 53, [l("Tennis", "Djokovic to win", 1.39, true, "Moneyline", "Match Winner", "1st Set", "ATP"), l("Tennis", "Alcaraz to win", 1.76, true, "Moneyline", "Match Winner", null, "ATP"), l("Tennis", "Zverev to win", 1.75, true, "Moneyline", "Match Winner", null, "ATP")]),
  bet(237.23, 51, [l("Football", "Spain to win", 2.26, true, "Moneyline", "Match Winner", "2nd Half", "International")]),
  bet(275.04, 50, [l("Football", "Over 2.5 goals", 2.78, false, "Totals (Over/Under)", "Match Total", null, "Champions League")]),
  bet(199.97, 48, [l("Tennis", "Over 22.5 games", 2.35, true, "Totals (Over/Under)", "Match Total", null, "ATP")]),
  bet(66.89, 47, [l("Basketball", "Giannis over 29.5 points", 2.35, true, "Player Props", "Points", null, "NBA")]),
  bet(225.22, 45, [l("Football", "Sevilla to win", 4.09, false, "Moneyline", "Match Winner", "1st Half", "La Liga")]),
  bet(236.5, 44, [l("Football", "Betis to win", 2.46, true, "Moneyline", "Match Winner", "1st Half", "La Liga")]),
  bet(320, 42, [l("Basketball", "Booker over 23.5 points", 2.43, false, "Player Props", "Points", null, "NBA")]),
  bet(236.32, 41, [l("Ice Hockey", "Oilers to win", 2.52, true, "Moneyline", "Match Winner", null, "NHL")]),
  bet(12, 39, [l("Football", "Arsenal to win", 2.54, true, "Moneyline", "Match Winner", null, "Premier League")]),
  bet(314.83, 38, [l("Ice Hockey", "Over 6.5 goals", 1.51, false, "Totals (Over/Under)", "Match Total", null, "NHL")]),
  bet(204.27, 36, [l("Baseball", "Yankees -1.5", 2.56, true, "Spread / Handicap", "Spread", null, "MLB")]),
  bet(225.22, 34, [l("Football", "Inter to advance", 2.11, false, "Moneyline", "To Advance", null, "Champions League")]),
  bet(130.26, 33, [l("Football", "Brentford to win", 1.75, true, "Moneyline", "Match Winner", "1st Half", "Premier League"), l("Football", "West Ham to win", 1.7, true, "Moneyline", "Match Winner", "1st Half", "Premier League"), l("Football", "Spurs to win", 1.76, true, "Moneyline", "Match Winner", "1st Half", "Premier League")]),
  bet(236.13, 31, [l("Football", "Barcelona to win", 2.59, true, "Moneyline", "Match Winner", null, "La Liga")]),
  bet(275.04, 30, [l("Tennis", "Under 21.5 games", 2.69, false, "Totals (Over/Under)", "Match Total", null, "ATP")]),
  bet(20.26, 28, [l("Football", "Porto -1", 2.71, true, "Spread / Handicap", "Spread", null, "Premier League")]),
  bet(320, 27, [l("Basketball", "Tatum over 27.5 points", 3.29, false, "Player Props", "Points", null, "NBA")]),
  bet(235.83, 25, [l("Football", "Real Madrid to win", 2.71, true, "Moneyline", "Match Winner", null, "La Liga")]),
  bet(225.22, 24, [l("Ice Hockey", "Panthers to win", 2.04, false, "Moneyline", "Match Winner", null, "NHL")]),
  bet(235.72, 22, [l("Football", "PSG to advance", 2.76, true, "Moneyline", "To Advance", null, "Champions League")]),
  bet(225.22, 21, [l("Football", "Arsenal to advance", 2.79, false, "Moneyline", "To Advance", null, "Champions League")]),
  bet(235.46, 19, [l("Football", "Bayern to advance", 2.89, true, "Moneyline", "To Advance", "1st Half", "Champions League")]),
  bet(208.97, 17, [l("Football", "Over 9.5 corners", 2.88, true, "Match Props", "Corners", null, "La Liga")]),
  bet(275.04, 16, [l("Baseball", "Braves -1.5", 2.92, false, "Spread / Handicap", "Spread", null, "MLB")]),
  bet(122.16, 14, [l("Football", "Brighton to win", 1.65, true, "Moneyline", "Match Winner", "2nd Half", "Premier League"), l("Football", "Fulham to win", 1.33, true, "Moneyline", "Match Winner", null, "Premier League"), l("Football", "BTTS: yes", 2.83, true, "Match Props", "BTTS", null, "Premier League")]),
  bet(320, 13, [l("Football", "Isak to score", 2.55, false, "Player Props", "Goalscorer", null, "International")]),
  bet(144.89, 11, [l("Basketball", "SGA over 28.5 points", 3.56, true, "Player Props", "Points", "3rd Quarter", "NBA")]),
  bet(275.04, 10, [l("Crypto", "BTC above 100K by Friday", 3.73, false, "Price Direction", "Price Direction", null, null)]),
  bet(225.22, 8, [l("Football", "Atletico to win", 2.09, false, "Moneyline", "Match Winner", null, "La Liga")]),
  bet(12, 7, [l("Football", "Salah to score", 4.83, true, "Player Props", "Goalscorer", null, "Premier League")]),
  bet(320, 5, [l("Basketball", "Jokic over 26.5 points", 3.89, false, "Player Props", "Points", null, "NBA")]),
  bet(225.22, 4, [l("Football", "England to win", 2.74, false, "Moneyline", "Match Winner", null, "International")]),
  bet(101.85, 2, [l("American Football", "Burrow over 265.5 yards", 3.29, true, "Player Props", "Passing Yards", null, "NFL"), l("American Football", "Allen over 250.5 yards", 4.05, true, "Player Props", "Passing Yards", null, "NFL")]),
];
