import Link from "next/link";
import PhoneMock from "@/components/PhoneMock";
import StartTracking from "@/components/StartTracking";
import Wordmark from "@/components/Wordmark";
import { Beams, Grain } from "@/components/landing/Atmosphere";
import { CheckItem, DotGrid, Eyebrow, TrustRow } from "@/components/landing/Bits";
import InsightChip from "@/components/landing/InsightChip";
import { BookRow, BookTiles } from "@/components/landing/Sportsbooks";

// THE LANDING PAGE, BUILT TO THE OWNER'S MOCKUP.
//
// He sent a full page design and asked for it back, to the layout:
// "copy this layout. do everything you can to make the landing page
// look identical to this." So the composition below is his, not mine.
// Where I have departed from it, there is a comment saying why.
//
// His four extra instructions, all applied:
//   real product screen shots      PhoneMock, regenerated by makeshots
//   the brand purple               every accent comes from globals.css
//   beams pointing at the phones   Beams, aimed down the right column
//   no top menu                    the header is a wordmark and two
//                                  buttons, nothing else
//
// LIGHT IS THE PAGE. Dark mode still works, because the app has a theme
// switch and a visitor may arrive with one set, but every value below
// was chosen for the light version, which is the one he designed.

const FEATURES = [
  {
    title: "Track Every Bet",
    body: "Log bets across all sportsbooks and never lose track.",
  },
  {
    title: "Analyze & Discover",
    body: "Powerful analytics reveal patterns, leaks, and opportunities.",
  },
  {
    title: "Improve Results",
    body: "Use insights to make smarter decisions and protect your bankroll.",
  },
];

const CHECKS = [
  { title: "Paste a bet slip", body: "We'll read it and fill in the details." },
  { title: "Singles and parlays", body: "Track every bet type with ease." },
  { title: "Track key stats", body: "Profit, ROI, hit rate, and more." },
  { title: "Spot patterns", body: "Find what works, what doesn't, and why." },
];

const TRUST = ["Free to start", "No credit card", "Sync in seconds"];

// The three feature marks, in tinted tiles like the mockup's.
function FeatureIcon({ title }: { title: string }) {
  const common = {
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 1.7,
    strokeLinecap: "round" as const,
    strokeLinejoin: "round" as const,
    className: "h-6 w-6",
    "aria-hidden": true,
  };
  if (title === "Track Every Bet")
    return (
      <svg {...common}>
        <rect x="4" y="3" width="16" height="18" rx="2.5" />
        <path d="M8 8.5h5M8 12h5" />
        <path d="M8 15.6l1.4 1.4L12 14.4" />
      </svg>
    );
  if (title === "Analyze & Discover")
    return (
      <svg {...common}>
        <path d="M4 20V11M10 20V4M16 20v-6.5M22 20H2" />
      </svg>
    );
  return (
    <svg {...common}>
      <path d="M3 17.5 9 11l4 4 8-8.5" />
      <path d="M15 6.5h6v6" />
    </svg>
  );
}

// The three phones of the hero. Sized rather than transform scaled: a
// transform leaves the original box in the layout, which left 200px of
// dead air above the group on a phone.
function PhoneTrio({ base, priority = false }: { base: number; priority?: boolean }) {
  const outer = Math.round(base * 0.8);
  const overlap = Math.round(base * 0.16);
  const drop = Math.round(base * 0.1);
  return (
    <div className="flex items-end justify-center">
      <PhoneMock
        src="/shots/track-dark.png"
        srcLight="/shots/track-light.png"
        alt="The Track page, showing a tracking balance and the ways to log a bet"
        width={outer}
        angle={14}
        lift={-drop}
        style={{ marginRight: -overlap }}
      />
      <PhoneMock
        src="/shots/performance-dark.png"
        srcLight="/shots/performance-light.png"
        alt="The Performance page, showing profit over time"
        width={base}
        priority={priority}
        className="z-10"
      />
      <PhoneMock
        src="/shots/research-dark.png"
        srcLight="/shots/research-light.png"
        alt="The Research page"
        width={outer}
        angle={-14}
        lift={-drop}
        style={{ marginLeft: -overlap }}
      />
    </div>
  );
}

const DISPLAY = "font-display font-extrabold tracking-[-0.035em]";
const SHELL = "mx-auto w-full max-w-6xl px-5 sm:px-8";

export default function LandingPage() {
  return (
    <main className="overflow-x-hidden bg-white text-neutral-900 dark:bg-[#04081B] dark:text-white">
      {/* ================= HEADER =================
          No menu. The owner cut Features, How It Works, Pricing and
          About: there is nothing behind any of them, and four dead
          links at the top of a page is the fastest way to look unfinished. */}
      <header className={`${SHELL} flex items-center justify-between py-5`}>
        <Wordmark className="text-[22px]" />
        <div className="flex items-center gap-2.5">
          <Link
            href="/login"
            className="rounded-xl border border-neutral-900/10 px-4 py-2.5 text-sm font-bold text-neutral-700 transition-colors hover:bg-neutral-900/[0.04] dark:border-white/15 dark:text-white/90 dark:hover:bg-white/[0.06]"
          >
            Log in
          </Link>
          <Link
            href="/signup"
            className="rounded-xl bg-gradient-to-b from-brand-top to-brand-bottom px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-brand-top/25 transition-opacity hover:opacity-95"
          >
            Start Tracking
          </Link>
        </div>
      </header>

      {/* ================= HERO ================= */}
      <section className="relative isolate overflow-hidden">
        {/* THE BEAMS, AIMED AT THE PHONES. The owner: "add that purple
            background glow in the hero section, where it feels like
            light beams pointing down to the phones." They sit in the
            right half only, so the left column stays clean type. */}
        <div className="pointer-events-none absolute inset-y-0 right-0 hidden w-[62%] lg:block">
          <Beams />
          <div
            aria-hidden="true"
            className="absolute left-1/2 top-0 h-[560px] w-[820px] -translate-x-1/2 rounded-[50%] bg-brand-top/[0.16] blur-3xl dark:bg-brand-mark/25"
          />
        </div>
        {/* On a phone the beams sit behind everything, because there is
            no second column to keep them out of. */}
        <div className="pointer-events-none absolute inset-x-0 top-0 h-[70%] lg:hidden">
          <Beams />
        </div>
        <Grain />

        <div className={`${SHELL} relative`}>
          <div className="grid items-center gap-10 pb-14 pt-8 lg:grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)] lg:gap-6 lg:pb-24 lg:pt-10">
            <div className="min-w-0 text-center lg:text-left">
              <Eyebrow>The smarter way to bet</Eyebrow>

              <h1
                className={`${DISPLAY} mt-6 text-[3.1rem] leading-[0.95] sm:text-[4rem] lg:text-[4.5rem]`}
              >
                Know
                <br className="hidden sm:block" />{" "}
                Your{" "}
                <span className="text-brand-top dark:text-brand-mark">
                  Game.
                </span>
              </h1>

              <p className="mt-6 text-xl font-bold leading-snug text-neutral-700 dark:text-neutral-200 sm:text-[26px]">
                Track every bet. Discover patterns.
                <br className="hidden sm:block" /> Find your edge.
              </p>

              <p className="mx-auto mt-5 max-w-md text-[15px] leading-relaxed text-neutral-500 dark:text-neutral-400 lg:mx-0">
                Celebet is the sports betting companion that helps you track
                your bets, uncover patterns, and improve your results.
              </p>

              <div className="mt-8 flex justify-center lg:justify-start">
                <StartTracking label="Start Tracking — It's Free" />
              </div>

              <div className="mt-5 flex justify-center lg:justify-start">
                <TrustRow items={TRUST} />
              </div>
            </div>

            <div className="relative w-full min-w-0">
              <div className="sm:hidden">
                <PhoneTrio base={150} priority />
              </div>
              <div className="hidden sm:block lg:hidden">
                <PhoneTrio base={215} />
              </div>
              <div className="hidden lg:block">
                <PhoneTrio base={252} />
              </div>

              <InsightChip
                className="absolute -bottom-6 -right-4 z-30 hidden w-[215px] xl:block"
                label="Biggest loss"
                headline="Basketball 3-legger keeps costing you."
                value="-$440.00"
                tone="down"
              />
            </div>
          </div>
        </div>
      </section>

      {/* ================= THE BOOKS ================= */}
      <section className={`${SHELL} pb-14`}>
        <div className="flex flex-col items-center gap-7 sm:flex-row sm:gap-12">
          <p className="shrink-0 text-center text-[11px] font-bold uppercase leading-[1.5] tracking-[0.12em] text-brand-top dark:text-brand-mark sm:max-w-[150px] sm:text-left">
            Trusted by bettors from 30+ sportsbooks
          </p>
          <BookRow />
        </div>
      </section>

      {/* ================= THREE FEATURES ================= */}
      <section className={`${SHELL} border-t border-neutral-900/[0.07] py-14 dark:border-white/[0.07]`}>
        <div className="grid gap-10 sm:grid-cols-3 sm:gap-8">
          {FEATURES.map(({ title, body }) => (
            <div key={title} className="flex gap-4">
              <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-brand-top/[0.08] text-brand-top dark:bg-brand-mark/[0.14] dark:text-brand-mark">
                <FeatureIcon title={title} />
              </span>
              <span className="min-w-0">
                <span className="block text-[17px] font-bold">{title}</span>
                <span className="mt-1.5 block text-sm leading-relaxed text-neutral-500 dark:text-neutral-400">
                  {body}
                </span>
              </span>
            </div>
          ))}
        </div>
      </section>

      {/* ================= POWERFUL ANALYTICS ================= */}
      <section className={`${SHELL} border-t border-neutral-900/[0.07] py-16 dark:border-white/[0.07] sm:py-20`}>
        <div className="grid items-center gap-14 lg:grid-cols-2 lg:gap-16">
          <div>
            <Eyebrow>Powerful Analytics</Eyebrow>
            <h2
              className={`${DISPLAY} mt-6 text-[2.5rem] leading-[0.95] sm:text-[3.25rem]`}
            >
              See What
              <br />
              Others{" "}
              <span className="text-brand-top dark:text-brand-mark">Miss.</span>
            </h2>
            <p className="mt-5 max-w-md text-[15px] leading-relaxed text-neutral-500 dark:text-neutral-400">
              Turn your betting history into actionable insights and make better
              decisions.
            </p>

            <ul className="mt-9 space-y-5">
              {CHECKS.map((c) => (
                <CheckItem key={c.title} {...c} />
              ))}
            </ul>
          </div>

          <div className="relative flex justify-center">
            <DotGrid className="-left-2 top-4 hidden h-[180px] w-[150px] sm:block" />
            <div
              aria-hidden="true"
              className="pointer-events-none absolute -right-10 top-10 h-[420px] w-[420px] rounded-[50%] bg-brand-top/[0.07] blur-3xl dark:bg-brand-mark/15"
            />
            <div className="relative">
              <PhoneMock
                src="/shots/performance-dark.png"
                srcLight="/shots/performance-light.png"
                alt="Profit over time, with staked, returned and ROI"
                width={272}
              />
            </div>
            <InsightChip
              className="absolute -right-8 bottom-20 z-30 hidden w-[210px] lg:block"
              label="Trending"
              headline="3 weeks in a row of better results."
              value="+$2,119"
            />
          </div>
        </div>
      </section>

      {/* ================= COMING SOON =================
          Labelled, because the Connect tile in the app does nothing
          yet. A promise marked as a promise is fine. */}
      <section className={`${SHELL} border-t border-neutral-900/[0.07] py-16 dark:border-white/[0.07]`}>
        <div className="grid items-center gap-10 lg:grid-cols-2 lg:gap-16">
          <div>
            <Eyebrow tone="soon">Coming soon</Eyebrow>
            <h2
              className={`${DISPLAY} mt-6 text-[2rem] leading-[1.05] sm:text-[2.5rem]`}
            >
              Sync from 30+ sportsbooks and daily fantasy sites.
            </h2>
            <p className="mt-5 max-w-md text-[15px] leading-relaxed text-neutral-500 dark:text-neutral-400">
              Connect your accounts and your bets arrive on their own. Until
              then, paste a bet slip or add one by hand in a few seconds.
            </p>
          </div>

          <div>
            <BookTiles />
            <p className="mt-4 text-[13px] text-neutral-500 dark:text-neutral-400">
              More coming soon
            </p>
          </div>
        </div>
      </section>

      {/* ================= THE CLOSE ================= */}
      <section className={`${SHELL} pb-16`}>
        <div className="relative overflow-hidden rounded-3xl border border-brand-top/10 bg-gradient-to-br from-cta-1 via-cta-2 to-cta-3 px-6 py-12 dark:border-white/[0.08] dark:from-cta-dark-1 dark:via-cta-dark-2 dark:to-cta-dark-3 sm:px-12 sm:py-14">
          <Grain />
          <div className="relative grid items-center gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(0,0.72fr)]">
            <div className="text-center lg:text-left">
              <h2
                className={`${DISPLAY} text-[2.25rem] leading-[1] sm:text-[2.75rem]`}
              >
                Ready to Get an{" "}
                <span className="text-brand-top dark:text-brand-mark">
                  Edge?
                </span>
              </h2>
              <p className="mx-auto mt-4 max-w-lg text-[15px] leading-relaxed text-neutral-600 dark:text-neutral-400 lg:mx-0">
                Join thousands of bettors who track smarter, win more, and
                protect their bankroll.
              </p>
              <div className="mt-7 flex justify-center lg:justify-start">
                <StartTracking label="Start Tracking — It's Free" />
              </div>
              <div className="mt-5 flex justify-center lg:justify-start">
                <TrustRow items={TRUST} />
              </div>
            </div>

            {/* The angled phone, bleeding out of the panel's lower right
                exactly as in the mockup. Hidden below lg, where there is
                no room for it to bleed into. */}
            <div className="relative hidden h-[350px] lg:block">
              <div className="absolute -bottom-[72px] -right-2 rotate-[8deg]">
                <PhoneMock
                  src="/shots/performance-dark.png"
                  srcLight="/shots/performance-light.png"
                  alt="Profit over time"
                  width={214}
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ================= FOOTER ================= */}
      <footer className={`${SHELL} border-t border-neutral-900/[0.07] pb-10 pt-9 dark:border-white/[0.07]`}>
        <div className="flex flex-col items-center gap-6 sm:flex-row sm:justify-between">
          <Wordmark className="text-lg" />

          <nav className="flex items-center gap-7 text-sm font-semibold text-neutral-500 dark:text-neutral-400">
            <Link href="/terms" className="transition-colors hover:text-neutral-900 dark:hover:text-white">
              Terms
            </Link>
            <Link href="/privacy" className="transition-colors hover:text-neutral-900 dark:hover:text-white">
              Privacy
            </Link>
          </nav>

          <a
            href="https://instagram.com/gocelebet"
            target="_blank"
            rel="noreferrer"
            aria-label="Celebet on Instagram"
            className="flex h-9 w-9 items-center justify-center rounded-xl text-neutral-500 transition-colors hover:bg-neutral-900/[0.05] hover:text-neutral-700 dark:text-neutral-400 dark:hover:bg-white/[0.06] dark:hover:text-white"
          >
            <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth={1.8} aria-hidden="true">
              <rect x="3" y="3" width="18" height="18" rx="5" />
              <circle cx="12" cy="12" r="4" />
              <circle cx="17.4" cy="6.6" r="1.1" fill="currentColor" stroke="none" />
            </svg>
          </a>
        </div>

        <div className="mt-8 space-y-2 border-t border-neutral-900/[0.07] pt-6 text-center text-xs leading-relaxed text-neutral-500 dark:border-white/[0.07] dark:text-neutral-400">
          <p>
            This platform is meant for entertainment purposes only. If you or
            someone you know has a gambling problem and wants help, call 1-800
            GAMBLER. Celebet is intended for adult use only.
          </p>
          <p>Celebet&trade; is a trademark of Peak Street 6 LLC.</p>
        </div>
      </footer>
    </main>
  );
}
