import Link from "next/link";
import MicroLabel from "@/components/MicroLabel";
import PhoneMock from "@/components/PhoneMock";
import StartTracking from "@/components/StartTracking";
import Wordmark from "@/components/Wordmark";

// THE LANDING PAGE. Copy is the owner's, word for word.
//
// It replaces a page whose phone still showed a black balance card and
// Today/Week/Month/Year tiles, months after both were deleted from the
// app. The phones here are PhoneMock with real screenshots inside,
// regenerated by makeshots.mjs, so that cannot happen again.
//
// THREE CLAIMS ARE DELIBERATELY NOT ON THIS PAGE, all removed with the
// owner's agreement:
//   "1M+ bets tracked" and "4.8 star rating"   neither is true
//   "line movement in real time"               does not exist
//   App Store and Google Play badges           there is no app to link
// Account syncing survives only as a Coming soon strip, clearly marked,
// because the Connect tile in the app does nothing yet. Everything else
// below is a thing the app does today.

const PILLARS = [
  { title: "Track", body: "Every bet, any app." },
  { title: "Analyze", body: "What pays, what leaks." },
  { title: "Improve", body: "Patterns from your own numbers." },
];

const TRUTHS = [
  {
    title: "Paste a bet slip",
    body: "Celebet reads the screenshot and fills the form in. Check it and it is tracked.",
  },
  {
    title: "Singles and parlays",
    body: "Nine sports, with every leg counted where it belongs.",
  },
  {
    title: "Numbers that keep up",
    body: "Profit, ROI, hit rate and your best and worst sports, updated as bets settle.",
  },
];

// The four key features, as small line marks. Ink, not colour: a
// coloured icon on a landing page competes with the one button that
// matters.
function KeyIcon({ name }: { name: string }) {
  const common = {
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 1.7,
    strokeLinecap: "round" as const,
    strokeLinejoin: "round" as const,
    className: "h-5 w-5",
    "aria-hidden": true,
  };
  if (name === "Track All Bets")
    return (
      <svg {...common}>
        <rect x="4" y="3" width="16" height="18" rx="2.5" />
        <path d="M8.5 9h7M8.5 13h7M8.5 17h4" />
      </svg>
    );
  if (name === "Powerful Analytics")
    return (
      <svg {...common}>
        <path d="M4 20V10M10 20V4M16 20v-7M22 20H2" />
      </svg>
    );
  if (name === "Find Patterns")
    return (
      <svg {...common}>
        <path d="M3 16l5-6 4 4 4-7 5 5" />
        <circle cx="8" cy="10" r="1.4" />
        <circle cx="16" cy="7" r="1.4" />
      </svg>
    );
  return (
    <svg {...common}>
      <path d="M12 20V7M12 7l-5 5M12 7l5 5" />
      <path d="M4 4h16" />
    </svg>
  );
}

const KEYS = [
  "Track All Bets",
  "Powerful Analytics",
  "Find Patterns",
  "Improve Results",
];

export default function LandingPage() {
  return (
    <main className="min-h-svh overflow-x-hidden bg-[#F7F7FB] text-neutral-900 dark:bg-[#04081B] dark:text-white">
      {/* ONE. THE HERO. Everything needed to decide is above the fold:
          what it is, what it does, and a box to type an email into. */}
      <section className="relative overflow-hidden">
        {/* A single wash of brand light behind the phones. On light it
            is barely there; on dark it is what stops the page reading
            as a black rectangle. */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute -top-40 left-1/2 h-[600px] w-[900px] -translate-x-1/2 rounded-[50%] bg-brand-top/[0.07] blur-3xl dark:bg-brand-mark/20"
        />

        <div className="relative mx-auto w-full max-w-6xl px-5 pt-6 sm:px-8">
          <header className="flex items-center justify-between">
            <Wordmark className="text-xl" />
            <Link
              href="/login"
              className="rounded-xl px-3 py-2 text-sm font-bold text-neutral-600 dark:text-neutral-300"
            >
              Log in
            </Link>
          </header>

          <div className="grid items-center gap-10 pt-12 pb-16 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.05fr)] lg:gap-8 lg:pt-16 lg:pb-24">
            <div className="min-w-0">
              <h1 className="text-[3rem] font-bold leading-[0.95] tracking-tight sm:text-6xl lg:text-7xl">
                Know Your
                <br />
                Game.
              </h1>
              <p className="mt-5 text-lg font-semibold text-neutral-500 dark:text-neutral-400 sm:text-xl">
                Track Every Bet. Discover Patterns. Find Your Edge.
              </p>

              <div className="mt-8">
                <StartTracking />
              </div>

              {/* The four key features. Under the button, because they
                  answer the question you have after you have already
                  decided to look, not before. */}
              <ul className="mt-10 grid grid-cols-2 gap-x-6 gap-y-5 sm:grid-cols-4 lg:gap-x-4">
                {KEYS.map((name) => (
                  <li key={name} className="flex flex-col gap-2">
                    <span className="text-neutral-500 dark:text-neutral-400">
                      <KeyIcon name={name} />
                    </span>
                    <span className="text-sm font-semibold leading-snug">
                      {name}
                    </span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Three phones, centre forward. The owner picked this
                arrangement. The outer two are turned and dropped back
                so the middle screen stays the readable one. */}
            {/* THE GROUP IS SCALED, NOT RESIZED. PhoneMock takes its
                width as a number and writes it as an inline style, and
                an inline width beats any class, so a responsive
                sm:w-[...] on these did nothing at all: on a phone the
                three of them came to 439px inside a 393px screen, the
                grid grew to fit them, and the headline ran off the
                right edge. One transform on the wrapper scales the
                whole arrangement and keeps the overlaps exact.
                overflow-hidden on the wrapper is the guarantee: if a
                future change makes them too wide again, they clip
                instead of stretching the page. */}
            <div className="w-full overflow-hidden">
              <div className="flex origin-center scale-[0.72] items-center justify-center sm:scale-90 lg:scale-100 lg:justify-end">
                <PhoneMock
                  src="/shots/track-dark.png"
                  alt="The Track page, showing a tracking balance and the ways to log a bet"
                  width={175}
                  angle={22}
                  lift={-16}
                  className="-mr-8 opacity-90"
                />
                <PhoneMock
                  src="/shots/performance-dark.png"
                  alt="The Performance page, showing profit over time"
                  width={228}
                  lift={26}
                  glow
                  priority
                  className="z-10"
                />
                <PhoneMock
                  src="/shots/research-dark.png"
                  alt="The Research page"
                  width={175}
                  angle={-22}
                  lift={-16}
                  className="-ml-8 opacity-90"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* TWO. WHAT IT IS, in the owner's three words. */}
      <section className="border-y border-neutral-900/[0.07] bg-white dark:border-white/[0.07] dark:bg-[#0E1228]">
        <div className="mx-auto w-full max-w-6xl px-5 py-14 sm:px-8 sm:py-20">
          <p className="max-w-2xl text-xl font-semibold leading-snug sm:text-2xl">
            Celebet is the sports betting companion that helps you track your
            bets, uncover patterns, and improve your results.
          </p>

          <div className="mt-10 grid gap-8 sm:grid-cols-3 sm:gap-10">
            {PILLARS.map(({ title, body }) => (
              <div key={title}>
                <p className="text-lg font-bold">{title}</p>
                <p className="mt-1.5 text-sm leading-relaxed text-neutral-500 dark:text-neutral-400">
                  {body}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* THREE. THE PROOF SECTION. One phone, big enough to read, and
          three things the app genuinely does beside it. */}
      <section className="mx-auto w-full max-w-6xl px-5 py-16 sm:px-8 sm:py-24">
        <div className="grid items-center gap-12 lg:grid-cols-2 lg:gap-16">
          <div>
            {/* No purple eyebrow. Purple has one job in this product
                and it is something you press. */}
            <MicroLabel>Powerful Analytics</MicroLabel>
            <h2 className="mt-3 text-[2rem] font-bold leading-tight tracking-tight sm:text-4xl">
              See What Others Miss.
            </h2>
            <p className="mt-4 max-w-lg text-base leading-relaxed text-neutral-500 dark:text-neutral-400">
              Celebet turns your betting history into actionable insights so you
              can make smarter decisions and protect your bankroll.
            </p>

            <dl className="mt-8 space-y-6">
              {TRUTHS.map(({ title, body }) => (
                <div key={title}>
                  <dt className="text-sm font-bold">{title}</dt>
                  <dd className="mt-1 max-w-lg text-sm leading-relaxed text-neutral-500 dark:text-neutral-400">
                    {body}
                  </dd>
                </div>
              ))}
            </dl>
          </div>

          <div className="flex justify-center lg:justify-end">
            <PhoneMock
              src="/shots/performance-light.png"
              alt="Profit over time, with staked, returned and ROI"
              width={250}
              angle={-10}
              chrome="#F7F7FB"
              onDark={false}
              className="dark:hidden"
            />
            <PhoneMock
              src="/shots/performance-dark.png"
              alt="Profit over time, with staked, returned and ROI"
              width={250}
              angle={-10}
              glow
              className="hidden dark:block"
            />
          </div>
        </div>
      </section>

      {/* FOUR. THE COMING SOON STRIP. Kept at the owner's request and
          labelled, because the Connect tile in the app does nothing
          yet. A promise marked as a promise is fine. The same sentence
          without the label would be a lie. */}
      <section className="mx-auto w-full max-w-6xl px-5 pb-16 sm:px-8 sm:pb-24">
        <div className="rounded-3xl border border-neutral-900/[0.07] bg-white px-6 py-8 text-center dark:border-white/[0.07] dark:bg-[#0E1228] sm:px-10 sm:py-10">
          <span className="inline-block rounded-full bg-[#22C55E]/15 px-3 py-1 text-[#22C55E]">
            <MicroLabel className="!text-[#22C55E]">Coming soon</MicroLabel>
          </span>
          <p className="mx-auto mt-4 max-w-xl text-xl font-bold leading-snug sm:text-2xl">
            Sync from 30+ sportsbooks and daily fantasy sites.
          </p>
          <p className="mx-auto mt-3 max-w-xl text-sm leading-relaxed text-neutral-500 dark:text-neutral-400">
            Connect your accounts and your bets arrive on their own. Until then,
            paste a bet slip or add one by hand in a few seconds.
          </p>
        </div>
      </section>

      {/* FIVE. THE CLOSE. The same field again, because someone who
          read the whole page should not have to scroll back up. */}
      <section className="border-t border-neutral-900/[0.07] bg-white dark:border-white/[0.07] dark:bg-[#0E1228]">
        <div className="mx-auto flex w-full max-w-6xl flex-col items-center px-5 py-16 text-center sm:px-8 sm:py-20">
          <h2 className="text-[2rem] font-bold leading-tight tracking-tight sm:text-4xl">
            Know Your Game.
          </h2>
          <p className="mt-3 text-base font-semibold text-neutral-500 dark:text-neutral-400">
            Track Every Bet. Discover Patterns. Find Your Edge.
          </p>
          <div className="mt-8 flex justify-center">
            <StartTracking />
          </div>
        </div>
      </section>

      <footer className="mx-auto w-full max-w-6xl px-5 py-10 sm:px-8">
        <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-between">
          <Wordmark className="text-base" />
          <nav className="flex items-center gap-6 text-sm font-semibold text-neutral-600 dark:text-neutral-300">
            <Link href="/terms">Terms</Link>
            <Link href="/privacy">Privacy</Link>
            <a
              href="https://instagram.com/gocelebet"
              target="_blank"
              rel="noreferrer"
            >
              @gocelebet
            </a>
          </nav>
        </div>

        <div className="mt-8 space-y-2 border-t border-neutral-900/[0.07] pt-6 text-center text-xs leading-relaxed text-neutral-500 dark:border-white/[0.07] dark:text-neutral-400">
          <p>
            This platform is meant for entertainment purposes only. If you or
            someone you know has a gambling problem and wants help, call 1-800
            GAMBLER. Celebet is intended for adult use only.
          </p>
          <p>Celebet&trade; is a trademark of Peak Street 6 LLC.</p>
        </div>
      </footer>
    </main>
  );
}
