import type { BetWithLegs } from "@/lib/types";
import { migrateManualLabel } from "@/lib/taxonomy";

// GENERATED BY gen.mjs. Edit that, not this, or the totals stop adding
// up. This folder is gitignored, so none of it reaches production.
//
// THIS IS THE SHARED FIXTURE. The Track preview (../data.ts) imports it
// and adds two pending bets, so both pages describe ONE account. They
// used to be two unrelated sets, which is fine for a design check and
// useless for a product photo.
//
// The owner pinned four figures himself (August 2026) and everything
// else is solved backwards from them:
//   tracking balance   $3,851
//   net profit         +$2,387   (open stakes included, so it is $250
//                                 below the settled figure)
//   best sport         Football, +$757, nothing else may reach it
//   stakes             sized against the balance. They ran up to $1,650
//                      on a $1,464 starting bankroll, which is a bet
//                      nobody could have placed.
// Now: 79 settled bets, $11,620 staked, 22.7% ROI, biggest stake $290.
//
// Per-sport money is exact because every parlay keeps BOTH legs inside
// one sport. A mixed parlay splits its profit across sports by leg
// odds, which is correct and makes an exact per-sport target
// unsolvable by hand.
//
// The set also carries the three Key Insight statements:
//   strength   Football, the clear winner over 15 picks
//   weakness   Basketball Player Props: Points, a clear loser
//   trend      three finished weeks, each better than the last

function daysAgo(days: number, hour = 18): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

let n = 0;
// Demo legs are written in the old curated labels; this converts
// them through the same legacy map phase12 used, so the preview
// shows the canonical taxonomy.
function demoTaxonomy(label: string | null): {
  subcategory: string | null;
  market: string | null;
  period: string | null;
  competition: string | null;
  provider_market: string | null;
} {
  const migrated = label ? migrateManualLabel(label) : null;
  return {
    subcategory: migrated?.category ?? label,
    market: migrated?.market ?? null,
    period: migrated?.period ?? null,
    competition: null,
    provider_market: null,
  };
}

function single(
  sport: BetWithLegs["legs"][number]["sport"],
  subcategory: string | null,
  description: string,
  stake: number,
  odds: number,
  won: boolean,
  days: number
): BetWithLegs {
  n += 1;
  const payout = won ? Math.round(stake * odds * 100) / 100 : 0;
  return {
    id: `x${n}`,
    stake,
    total_odds: odds,
    status: won ? "won" : "lost",
    placed_at: daysAgo(days, 9),
    settled_at: daysAgo(days),
    payout,
    cashed_out: false,
    bet_buys: [],
    legs: [
      {
        id: `x${n}a`,
        sport,
        description,
        odds,
        result: won ? "won" : "lost",
        ...demoTaxonomy(subcategory),
      },
    ],
  };
}

function parlay(
  legs: {
    sport: BetWithLegs["legs"][number]["sport"];
    subcategory: string | null;
    description: string;
    odds: number;
    won: boolean;
  }[],
  stake: number,
  days: number
): BetWithLegs {
  n += 1;
  const won = legs.every((l) => l.won);
  const odds = Math.round(legs.reduce((acc, l) => acc * l.odds, 1) * 10000) / 10000;
  return {
    id: `x${n}`,
    stake,
    total_odds: odds,
    status: won ? "won" : "lost",
    placed_at: daysAgo(days, 9),
    settled_at: daysAgo(days),
    payout: won ? Math.round(stake * odds * 100) / 100 : 0,
    cashed_out: false,
    bet_buys: [],
    legs: legs.map((l, i) => ({
      id: `x${n}${i}`,
      sport: l.sport,
      description: l.description,
      odds: l.odds,
      result: l.won ? "won" : "lost",
      ...demoTaxonomy(l.subcategory),
    })),
  };
}

// Newest first. The dates are searched for, not laid out in order: the
// three finished weeks have to rise or the "Trending up" insight stops
// appearing, and the chart has to dip into the red early, because a
// line that only ever climbs looks invented.
export const performanceBets: BetWithLegs[] = [
  single("Baseball", "Win-bet / Moneyline", "Reds ML", 200, 2.1, false, 27),
  single("Basketball", "Player Props: Points", "Tatum over 24.5", 80, 1.9, false, 26),
  single("Basketball", "Player Props: Points", "Embiid over 30.5", 260, 1.6, false, 26),
  single("Basketball", "Player Props: Points", "Young over 26.5", 120, 2.1, false, 26),
  single("Football", "Win-bet / Moneyline", "Real Madrid to win", 100, 1.6, true, 25),
  single("Ice Hockey", "Win-bet / Moneyline", "Maple Leafs ML", 80, 2.1, true, 25),
  single("American Football", "Goal Difference", "Eagles -2.5", 240, 1.8, false, 25),
  single("Tennis", null, "Zverev to win", 100, 2.6, false, 24),
  single("Ice Hockey", "Win-bet / Moneyline", "Avalanche ML", 100, 2.2, false, 24),
  single("Basketball", "Player Props: Points", "Brunson over 26.5", 80, 1.6, false, 24),
  single("Baseball", "Win-bet / Moneyline", "Dodgers ML", 120, 2.1, true, 23),
  single("Tennis", null, "Fritz to win", 260, 1.5, false, 23),
  single("American Football", "Win-bet / Moneyline", "Ravens ML", 160, 1.6, true, 23),
  single("Football", "Win-bet / Moneyline", "Arsenal to win", 230, 1.9, true, 22),
  single("Baseball", "Win-bet / Moneyline", "Phillies ML", 80, 1.5, true, 22),
  single("Baseball", "Win-bet / Moneyline", "Guardians ML", 260, 1.8, false, 22),
  single("Tennis", null, "Gauff to win", 60, 2.1, false, 21),
  single("Crypto", null, "ETH above 4.5k", 80, 2.1, true, 21),
  single("esports", null, "Navi to win", 240, 1.6, true, 21),
  single("Baseball", "Win-bet / Moneyline", "Mets ML", 180, 2.4, true, 20),
  parlay(
    [
      { sport: "Baseball", subcategory: "Win-bet / Moneyline", description: "Brewers ML", odds: 1.9, won: true },
      { sport: "Baseball", subcategory: "Win-bet / Moneyline", description: "Reds ML", odds: 2, won: true },
    ],
    180,
    20
  ),
  single("Ice Hockey", "Win-bet / Moneyline", "Bruins ML", 160, 1.7, true, 20),
  single("Baseball", "Win-bet / Moneyline", "Rangers ML", 180, 1.8, false, 19),
  single("American Football", "Win-bet / Moneyline", "Bills ML", 200, 1.6, true, 19),
  single("Basketball", "Player Props: Points", "Mitchell over 27.5", 260, 1.8, true, 19),
  single("Football", "Win-bet / Moneyline", "Feyenoord to win", 220, 2.2, false, 18),
  single("Tennis", null, "Sinner in straight sets", 70, 1.8, false, 18),
  single("Tennis", null, "Sabalenka to win", 60, 2, true, 18),
  single("esports", null, "T1 to win", 180, 1.8, true, 18),
  single("Ice Hockey", "Win-bet / Moneyline", "Golden Knights ML", 60, 2.6, false, 17),
  single("American Football", "Win-bet / Moneyline", "Lions ML", 140, 2.6, true, 17),
  single("Basketball", "Player Props: Points", "Morant over 23.5", 120, 2, false, 17),
  single("Baseball", "Win-bet / Moneyline", "Astros ML", 80, 2.4, true, 16),
  single("esports", null, "FaZe to win", 100, 1.5, false, 16),
  parlay(
    [
      { sport: "Basketball", subcategory: "Player Props: Points", description: "Tatum over 24.5", odds: 1.7, won: false },
      { sport: "Basketball", subcategory: "Player Props: Points", description: "Doncic over 29.5", odds: 2, won: false },
    ],
    240,
    16
  ),
  single("Tennis", null, "Alcaraz to win", 160, 1.8, true, 15),
  single("Tennis", null, "Swiatek to win", 100, 2.6, true, 15),
  single("Tennis", null, "Ruud to win", 260, 2.4, true, 15),
  single("Ice Hockey", "Win-bet / Moneyline", "Rangers ML", 60, 1.5, false, 14),
  single("esports", null, "G2 to win map 1", 60, 1.7, true, 14),
  single("Basketball", "Player Props: Points", "Doncic over 29.5", 260, 2.1, false, 14),
  single("Baseball", "Win-bet / Moneyline", "Padres ML", 60, 1.7, true, 13),
  single("Tennis", null, "Rybakina to win", 240, 2.2, true, 13),
  single("American Football", "Goal Difference", "49ers -6.5", 110, 2.2, false, 13),
  single("Football", "Win-bet / Moneyline", "Sevilla to win", 200, 1.8, true, 12),
  single("Ice Hockey", "Win-bet / Moneyline", "Panthers ML", 120, 1.7, true, 12),
  single("Basketball", "Player Props: Points", "Edwards over 25.5", 160, 1.6, true, 12),
  single("Baseball", "Win-bet / Moneyline", "Mariners ML", 80, 2.1, true, 11),
  single("Ice Hockey", "Win-bet / Moneyline", "Oilers ML", 210, 2.1, true, 11),
  single("Basketball", "Player Props: Points", "Sabonis over 19.5", 220, 2, true, 11),
  single("Football", "Win-bet / Moneyline", "PSG to win", 60, 1.7, false, 10),
  single("Football", "Goal Difference", "Porto -1", 100, 2, true, 10),
  single("esports", null, "Fnatic to win", 80, 1.6, false, 10),
  single("Basketball", "Player Props: Points", "Booker over 25.5", 60, 2, false, 10),
  single("Football", "Win-bet / Moneyline", "Roma to win", 140, 2.6, false, 9),
  parlay(
    [
      { sport: "Football", subcategory: "Win-bet / Moneyline", description: "Benfica to win", odds: 1.8, won: true },
      { sport: "Football", subcategory: "Win-bet / Moneyline", description: "Lyon to win", odds: 2, won: true },
    ],
    80,
    9
  ),
  single("Crypto", null, "SOL above 250", 260, 1.6, false, 9),
  single("Football", "Points Total", "Over 2.5 goals", 140, 2.6, true, 8),
  single("Crypto", null, "ETH above 4k", 260, 2.2, true, 8),
  single("Crypto", null, "ETH above 5k", 60, 1.6, false, 8),
  single("Football", "Win-bet / Moneyline", "Napoli to win", 160, 1.5, true, 7),
  single("Baseball", "Win-bet / Moneyline", "Yankees ML", 100, 2.6, true, 7),
  single("Crypto", null, "BTC above 100k", 100, 1.5, true, 7),
  single("Football", "Win-bet / Moneyline", "Inter to win", 90, 2.4, false, 6),
  single("Football", "Goal Difference", "Bayern -1.5", 180, 1.6, true, 6),
  single("Baseball", "Win-bet / Moneyline", "Braves ML", 100, 2, false, 6),
  parlay(
    [
      { sport: "Tennis", subcategory: null, description: "Alcaraz to win", odds: 1.5, won: false },
      { sport: "Tennis", subcategory: null, description: "Swiatek to win", odds: 2, won: false },
    ],
    80,
    5
  ),
  single("Basketball", "Player Props: Points", "Curry over 27.5", 210, 2.6, true, 5),
  single("Basketball", "Player Props: Points", "Haliburton over 20.5", 80, 2.2, false, 5),
  single("Football", "BTTS (Both Teams to Score)", "Both teams to score", 120, 2.1, true, 4),
  single("Baseball", "Win-bet / Moneyline", "Cubs ML", 140, 1.7, false, 4),
  single("Crypto", null, "BTC above 90k", 290, 2.1, true, 4),
  single("Tennis", null, "Medvedev to win", 220, 1.5, true, 3),
  single("Crypto", null, "SOL above 200", 90, 2, false, 3),
  single("American Football", "Goal Difference", "Chiefs -3", 200, 1.7, true, 3),
  single("Football", "Points Total", "Over 1.5 goals", 180, 2.4, false, 2),
  single("Football", "Win-bet / Moneyline", "Ajax to win", 140, 2.2, true, 2),
  single("Baseball", "Win-bet / Moneyline", "Giants ML", 240, 2, true, 2),
  single("Crypto", null, "BTC above 110k", 80, 1.7, true, 2),
];

// Two bets still riding. They live here rather than in ../data.ts so
// the ids keep counting from the same place. Their stakes are money
// already out of the balance, which is why Track shows $250 less
// profit than Performance.
export const pendingBets: BetWithLegs[] = [
  {
    id: "p1", stake: 150, total_odds: 2.15, status: "pending",
    placed_at: daysAgo(0, 9), settled_at: null, payout: null,
    cashed_out: false, bet_buys: [],
    legs: [
      { id: "p1a", sport: "Football", description: "Arsenal to win", odds: 1.47, result: "pending", ...demoTaxonomy("Win-bet / Moneyline") },
      { id: "p1b", sport: "Football", description: "Over 2.5 goals", odds: 1.46, result: "pending", ...demoTaxonomy("Points Total") },
    ],
  },
  {
    id: "p2", stake: 100, total_odds: 3.4, status: "pending",
    placed_at: daysAgo(0, 11), settled_at: null, payout: null,
    cashed_out: false, bet_buys: [],
    legs: [
      { id: "p2a", sport: "Tennis", description: "Sinner in straight sets", odds: 3.4, result: "pending", ...demoTaxonomy(null) },
    ],
  },
];

// The only money figure typed in by hand. Balance and net profit are
// derived from it and the bets, so the three can never drift apart:
// deposits + net profit = the $3,851 the owner asked for.
export const DEPOSITS = 1464;
